DECLARE
    table_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO table_count FROM user_tables WHERE table_name = 'WATERSTATUSCITIES';

    IF table_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE WATERSTATUSCITIESa (
            id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            status VARCHAR2(50),
            msg VARCHAR2(100),
            date_updated TIMESTAMP,
            city VARCHAR2(100)
        )';
    END IF;
END;
